name: "Bug Report"
description: "Report an issue with PowerTools"
labels: "bug"
body:
    - type: checkboxes
      id: low-effort-checks
      attributes:
          label: Please confirm
          description: Issues without all checks may be ignored/closed.
          options:
              - label: I have searched existing issues
              - label: This issue is not a duplicate of an existing one
              - label: I am doing something good
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected Behaviour
          description: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: actual-behaviour
      attributes:
          label: Actual Behaviour
          description: A clear and concise description of what actually happened.
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '.....'
              4. See error......
      validations:
          required: true
    - type: textarea
      id: extras
      attributes:
          label: Anything else?
          description: |
              Screenshots? Logs? Anything that will give more context about the problem!
              If applicable, add screenshots to help explain your problem.
              Please include the log (located at `/tmp/powertools.log`) if possible.
              Note: the log is deleted when the device is restarted.

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: dropdown
      id: version
      attributes:
          label: Version
          description: What version of PowerTools are you using? This is the version beside `powertools-rs` near the bottom of the plugin's UI.
          options:
              - 1.1.0 (Indev)
              - 1.0.5 (Latest stable)
              - 1.0.X (Out of date)
              - 0.7.X (Very out of date)
              - Not listed
      validations:
          required: true
    - type: dropdown
      id: platform
      attributes:
          label: Version
          description: What platform are you using PowerTools on?
          options:
              - Steam Deck
              - Holoiso
              - Not listed
      validations:
          required: true
